In [1]:
# --- Libraries
import os
import logging
import random
import warnings
import gc

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision
from sklearn.model_selection import KFold

2026-03-21 22:19:54.964474: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774131595.189861      20 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774131595.252085      20 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

In [2]:
# --- Configuration 

INPUT_ROOT = '/kaggle/input/csiro-biomass'
TRAIN_CSV  = os.path.join(INPUT_ROOT, 'train.csv')
TEST_CSV   = os.path.join(INPUT_ROOT, 'test.csv')

IMG_SIZE   = 256

BATCH_SIZE_PER_REPLICA = 16

# 2 Gpus
STRATEGY = tf.distribute.MirroredStrategy()
GLOBAL_BATCH_SIZE = BATCH_SIZE_PER_REPLICA * STRATEGY.num_replicas_in_sync

print(STRATEGY.num_replicas_in_sync)
print(GLOBAL_BATCH_SIZE)

# Mixed precision
mixed_precision.set_global_policy('mixed_float16')
print(mixed_precision.global_policy())

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
2
32
<DTypePolicy "mixed_float16">

I0000 00:00:1774131612.682458      20 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13757 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1774131612.685059      20 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13757 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5

In [3]:
# --- Data prep
raw_train_df = pd.read_csv(TRAIN_CSV)

# Pivot long to wide
train_df = raw_train_df.pivot(index='image_path', columns='target_name', values='target').reset_index()

# Paths (add the complete position of each image)
train_df['full_path'] = train_df['image_path'].apply(lambda x: os.path.join(INPUT_ROOT, x))

In [4]:
raw_train_df

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750
...,...,...,...,...,...,...,...,...,...
1780,ID983582017__Dry_Clover_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Clover_g,0.0000
1781,ID983582017__Dry_Dead_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Dead_g,0.0000
1782,ID983582017__Dry_Green_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Green_g,40.9400
1783,ID983582017__Dry_Total_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Total_g,40.9400
1784,ID983582017__GDM_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,GDM_g,40.9400

In [5]:
train_df

target_name,image_path,Dry_Clover_g,Dry_Dead_g,Dry_Green_g,Dry_Total_g,GDM_g,full_path
0,train/ID1011485656.jpg,0.0000,31.9984,16.2751,48.2735,16.2750,/kaggle/input/csiro-biomass/train/ID1011485656...
1,train/ID1012260530.jpg,0.0000,0.0000,7.6000,7.6000,7.6000,/kaggle/input/csiro-biomass/train/ID1012260530...
2,train/ID1025234388.jpg,6.0500,0.0000,0.0000,6.0500,6.0500,/kaggle/input/csiro-biomass/train/ID1025234388...
3,train/ID1028611175.jpg,0.0000,30.9703,24.2376,55.2079,24.2376,/kaggle/input/csiro-biomass/train/ID1028611175...
4,train/ID1035947949.jpg,0.4343,23.2239,10.5261,34.1844,10.9605,/kaggle/input/csiro-biomass/train/ID1035947949...
...,...,...,...,...,...,...,...
352,train/ID975115267.jpg,40.0300,0.0000,0.8000,40.8300,40.8300,/kaggle/input/csiro-biomass/train/ID975115267.jpg
353,train/ID978026131.jpg,24.6445,4.1948,12.0601,40.8994,36.7046,/kaggle/input/csiro-biomass/train/ID978026131.jpg
354,train/ID980538882.jpg,0.0000,1.1457,91.6543,92.8000,91.6543,/kaggle/input/csiro-biomass/train/ID980538882.jpg
355,train/ID980878870.jpg,32.3575,0.0000,2.0325,34.3900,34.3900,/kaggle/input/csiro-biomass/train/ID980878870.jpg
356,train/ID983582017.jpg,0.0000,0.0000,40.9400,40.9400,40.9400,/kaggle/input/csiro-biomass/train/ID983582017.jpg

In [6]:
# Scale Targets

# Scale Targets 
target_cols = ['Dry_Total_g', 'GDM_g', 'Dry_Green_g']   # Only these 3 bcs they should be the easist to predic (the others with math)
MAX_VAL = train_df[target_cols].max().max()             # Max value for scaling
TARGET_SCALER = MAX_VAL * 1.1

# Arrays
X_paths = train_df['full_path'].values                  
Y_targets = train_df[target_cols].values.astype('float32') / TARGET_SCALER   # Scaling

In [7]:
print(X_paths[:5])
print("\n")
print(Y_targets[:5])

['/kaggle/input/csiro-biomass/train/ID1011485656.jpg'
 '/kaggle/input/csiro-biomass/train/ID1012260530.jpg'
 '/kaggle/input/csiro-biomass/train/ID1025234388.jpg'
 '/kaggle/input/csiro-biomass/train/ID1028611175.jpg'
 '/kaggle/input/csiro-biomass/train/ID1035947949.jpg']


[[0.23632202 0.07967396 0.07967445]
 [0.03720566 0.03720566 0.03720566]
 [0.02961766 0.02961766 0.        ]
 [0.27026924 0.11865472 0.11865472]
 [0.16734909 0.05365692 0.05153033]]

In [8]:
# --- Load & pre-process

@tf.function
def load_image(path, label):
    # Load
    img = tf.io.read_file(path)
    img = tf.io.decode_jpeg(img, channels = 3)
    # Resize
    img = tf.image.resize(img,
                          [IMG_SIZE, IMG_SIZE],
                          preserve_aspect_ratio = False,
                          antialias = True
                         )
    # cast
    img = tf.cast(img, tf.float32)
    return img, label

@tf.function
def augment_geometric(img, label):
    # Random Flips
    img = tf.image.random_flip_left_right(img)
    img = tf.image.random_flip_up_down(img)

    # Random Rotate
    k = tf.random.uniform([], minval=0, maxval=4, dtype=tf.int32)
    img = tf.image.rot90(img, k)

    return img, label

# MixUp
MIXUP_LAYER = keras.layers.MixUp(alpha=0.034272, dtype='float32')

@tf.function
def apply_mixup(images, labels):
    images = tf.cast(images, tf.float32)
    labels = tf.cast(labels, tf.float32)
    outputs = MIXUP_LAYER({"images": images, "labels": labels})
    return outputs["images"], outputs["labels"]

# Model 
* Backbone: ConvNeXt-Base with Squeeze-and-Excitation attention
* Pooling: Learnable GeM Pooling (initial p=3.0)
* Head: Multi-branch regression structure with three dedicated paths for Total, GDM and Green biomass.
* Regularization: Combined Gaussian Noise, Dropout (0.3) and Swish activations

The model and the parameters were obtained with an Optuna Search.

In [9]:
# Generalized mean pooling (GeM)

@tf.keras.utils.register_keras_serializable()
class GeMPooling2D(layers.Layer):
    def __init__(self, p_init=2.24828, **kwargs):
        super().__init__(**kwargs)
        self.p_init = p_init

    def build(self, input_shape):
        self.p = self.add_weight(
            name="p_param",
            shape=(1,),
            initializer=keras.initializers.Constant(self.p_init),
            trainable=True
        )
        super().build(input_shape)

    def call(self, inputs):
        # (1/N * sum(x^p))^(1/p)
        x = tf.maximum(inputs, 1e-6)
        x = tf.pow(x, self.p)
        x = tf.reduce_mean(x, axis=[1, 2], keepdims=False)
        return tf.pow(x, 1.0 / self.p)

    # save/load the p_init value
    def get_config(self):
        config = super().get_config()
        config.update({"p_init": self.p_init})
        return config

In [10]:
# Attention block

def attention_block(inputs, ratio=16):
    """
    Squeeze-and-Excitation Block
    """
    # Number of features
    channels = inputs.shape[-1]
    # Squeeze: global Average Pooling to get a summary vector (Squeeze feature from (H, W, C) to (1, 1, C))
    x = layers.GlobalAveragePooling2D(keepdims=True)(inputs)
    # Excitation: bottleneck part, reduce param to learn (weights)
    x = layers.Dense(channels // ratio, activation='swish')(x)
    # Restoration: restore to the original dimension and weights can be put into the original feature map
    x = layers.Dense(channels, activation='sigmoid')(x)
    # Scale: multiply the original inputs by the calculated weights
    return layers.Multiply()([inputs, x])

In [11]:
# --- Model (+ Data Aug)

weights_path = '/kaggle/input/models/marcorosato/convnext-small/tensorflow2/default/1/convnext_small_notop.h5'

def build_model():
    inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))

    # Backbone
    base = keras.applications.ConvNeXtSmall(
        include_top=False,
        weights=None,
        input_shape=(IMG_SIZE, IMG_SIZE, 3),
        name = "convnext_backbone"
    )

    base.load_weights(weights_path)
    base.trainable = False

    x = base(inputs)
    x = attention_block(x)

    x = GeMPooling2D(p_init=2.24828)(x)

    # Gaussian Noise to regularize
    x = layers.GaussianNoise(0.037071)(x)

    # Dense layer + Dropout
    x = layers.Dense(384, activation='swish')(x)
    x = layers.Dropout(0.39424)(x)
    
    # Common dense layer 
    shared = layers.Dense(128, activation='swish')(x)

    # # Multi-Head Outputs
    # Head 1: Dry_Total_g
    h1 = layers.Dense(128, activation='swish')(shared)
    drop_h1 = layers.Dropout(0.29078)(h1)
    out1 = layers.Dense(1, activation='linear', name='total_head', dtype='float32')(drop_h1)
    # Head 2: GDM_g
    h2 = layers.Dense(128, activation='swish')(shared)
    drop_h2 = layers.Dropout(0.29078)(h2)
    out2 = layers.Dense(1, activation='linear', name='gdm_head', dtype='float32')(drop_h2)
    # Head 3: Dry_Green_g
    h3 = layers.Dense(128, activation='swish')(shared)
    drop_h3 = layers.Dropout(0.29078)(h3)
    out3 = layers.Dense(1, activation='linear', name='green_head', dtype='float32')(drop_h3)

    # Concatenate
    outputs = layers.Concatenate(axis=-1)([out1, out2, out3])

    return keras.Model(inputs, outputs)

model = build_model()

model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 256, 256,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ convnext_backbone   │ (None, 8, 8, 768) │ 49,454,688 │ input_layer[0][0] │
│ (Functional)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 1, 1, 768) │          0 │ convnext_backbon… │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 1, 1, 48)  │     36,912 │ global_average_p… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 1, 1, 768) │     37,632 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multiply (Multiply) │ (None, 8, 8, 768) │          0 │ convnext_backbon… │
│                     │                   │            │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ ge_m_pooling2d      │ (None, 768)       │          1 │ multiply[0][0]    │
│ (GeMPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gaussian_noise      │ (None, 768)       │          0 │ ge_m_pooling2d[0… │
│ (GaussianNoise)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 384)       │    295,296 │ gaussian_noise[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 384)       │          0 │ dense_2[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 128)       │     49,280 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 128)       │     16,512 │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 128)       │     16,512 │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 128)       │     16,512 │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 128)       │          0 │ dense_4[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 128)       │          0 │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 128)       │          0 │ dense_6[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast_1 (Cast)       │ (None, 128)       │          0 │ dropout_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast_2 (Cast)       │ (None, 128)       │          0 │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast_3 (Cast)       │ (None, 128)       │          0 │ dropout_3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ total_head (Dense)  │ (None, 1)         │        129 │ cast_1[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gdm_head (Dense)    │ (None, 1)         │        129 │ cast_2[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ green_head (Dense)  │ (None, 1)         │        129 │ cast_3[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast_4 (Cast)       │ (None, 1)         │          0 │ total_head[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast_5 (Cast)       │ (None, 1)         │          0 │ gdm_head[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast_6 (Cast)       │ (None, 1)         │          0 │ green_head[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 3)         │          0 │ cast_4[0][0],     │
│ (Concatenate)       │                   │            │ cast_5[0][0],     │
│                     │                   │            │ cast_6[0][0]      │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 49,923,732 (190.44 MB)

 Trainable params: 469,044 (1.79 MB)

 Non-trainable params: 49,454,688 (188.65 MB)

In [12]:
# --- Test data

raw_test_df = pd.read_csv(TEST_CSV)
unique_test_df = raw_test_df.drop_duplicates(subset=['image_path'])
test_paths = [os.path.join(INPUT_ROOT, p) for p in unique_test_df['image_path'].values]

@tf.function
def load_test_image(path):
    img = tf.io.read_file(path)
    img = tf.io.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])
    img = tf.cast(img, tf.float32)
    return img

test_ds = tf.data.Dataset.from_tensor_slices(test_paths)
test_ds = test_ds.map(load_test_image, num_parallel_calls=tf.data.AUTOTUNE).batch(GLOBAL_BATCH_SIZE)


# Test-Time Augmentation (TTA)
def predict_with_tta(model, dataset):
    """
    Data aug on test to improve results by average the results
    """
    p1 = model.predict(dataset, verbose=0)
    p2 = model.predict(dataset.map(lambda x: tf.image.flip_left_right(x)), verbose=0)  
    p3 = model.predict(dataset.map(lambda x: tf.image.flip_up_down(x)), verbose=0)
    return (p1 + p2 + p3) / 3.0

In [13]:
# --- K-fold Training Loop

N_FOLDS = 5

kf = KFold(n_splits = N_FOLDS, shuffle = True, random_state = 42)

fold_predictions = [] # Store predictions each fold

for fold, (train_idx, val_idx) in enumerate(kf.split(X_paths, Y_targets)):
    print(f"\n{'='*15} FOLD {fold+1}/{N_FOLDS} {'='*15}")
    
    # Split Data
    X_train, Y_train = X_paths[train_idx], Y_targets[train_idx]
    X_val, Y_val     = X_paths[val_idx],   Y_targets[val_idx]

    # Train dataset
    train_ds = tf.data.Dataset.from_tensor_slices((X_train, Y_train))
    train_ds = train_ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)         
    train_ds = train_ds.cache()                                                      
    train_ds = train_ds.shuffle(len(X_train), seed=42)                               
    train_ds = train_ds.map(augment_geometric, num_parallel_calls=tf.data.AUTOTUNE)  
    train_ds = train_ds.batch(GLOBAL_BATCH_SIZE)                                     
    train_ds = train_ds.map(apply_mixup, num_parallel_calls=tf.data.AUTOTUNE)        
    train_ds = train_ds.prefetch(tf.data.AUTOTUNE)

    # Val dataset
    val_ds = tf.data.Dataset.from_tensor_slices((X_val, Y_val))
    val_ds = val_ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
    val_ds = val_ds.cache()
    val_ds = val_ds.batch(GLOBAL_BATCH_SIZE)
    val_ds = val_ds.prefetch(tf.data.AUTOTUNE)

    
    keras.backend.clear_session()

    # Train Head

    print(f"\n--- Fold {fold+1}: Training Head ---")
    
    with STRATEGY.scope():
        
        model = build_model()
        
        optimizer_1 = tf.keras.optimizers.AdamW(
        learning_rate = 7e-4, 
        weight_decay = 0.0037214
        )
       
        model.compile(optimizer = optimizer_1,
                      loss=keras.losses.Huber(delta=0.84009),
                      metrics = ['mae']
                     )
    
        early_stop = keras.callbacks.EarlyStopping(monitor = 'val_loss',
                                           patience = 7,
                                           restore_best_weights = True
                                          )
        
        reduce_plateau = keras.callbacks.ReduceLROnPlateau(monitor = "val_loss",
                                                           factor = 0.1,
                                                           patience = 2,
                                                           verbose = 0                                                        
        )
        
    
    model.fit(train_ds,
              validation_data = val_ds,
              epochs = 20,
              callbacks = [early_stop, reduce_plateau],
              verbose = 1
             )


    
    # Fine Tune

    print(f"\n--- Fold {fold+1}: Fine Tuning ---")
    
    model.get_layer("convnext_backbone").trainable = True
    
    FINE_TUNE_BATCH_SIZE = GLOBAL_BATCH_SIZE // 2

    # Train
    ft_train_ds = tf.data.Dataset.from_tensor_slices((X_train, Y_train))
    ft_train_ds = ft_train_ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE).cache()
    ft_train_ds = ft_train_ds.shuffle(len(X_train), seed=42)
    ft_train_ds = ft_train_ds.map(augment_geometric, num_parallel_calls=tf.data.AUTOTUNE)
    ft_train_ds = ft_train_ds.batch(FINE_TUNE_BATCH_SIZE) 
    ft_train_ds = ft_train_ds.map(apply_mixup, num_parallel_calls=tf.data.AUTOTUNE).prefetch(tf.data.AUTOTUNE)

    # Val
    ft_val_ds = tf.data.Dataset.from_tensor_slices((X_val, Y_val))
    ft_val_ds = ft_val_ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE).cache()
    ft_val_ds = ft_val_ds.batch(FINE_TUNE_BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
            
    with STRATEGY.scope():

        # Cosine schedule -> Optuna LR & Cosine Decay
        lr_schedule_2 = keras.optimizers.schedules.CosineDecay(
            initial_learning_rate = 0.00006841,
            decay_steps = 1498,
            alpha = 0.01
        )
        
        optimizer_2 = tf.keras.optimizers.AdamW(
            learning_rate = lr_schedule_2, 
            weight_decay = 0.0037214
        )
    
        
        model.compile(optimizer = optimizer_2,
                      loss=keras.losses.Huber(delta=0.84009),
                      metrics = ['mae']
                     )
    
    ckpt_path = f"model_fold_{fold}.keras"
    ckpt = keras.callbacks.ModelCheckpoint(ckpt_path,              # Save Best Model Checkpoint
                                           save_best_only = True,
                                           monitor = 'val_loss',
                                           verbose = 0
                                          )  
    
    history = model.fit(ft_train_ds,
                        validation_data = ft_val_ds,
                        epochs = 30,
                        callbacks = [ckpt, early_stop],
                        verbose = 1
                       )


    # Memory clean up
    del model
    keras.backend.clear_session()
    gc.collect()
    
    
    # Predict on test data
    print(f"Predicting Fold {fold+1}")
    with STRATEGY.scope():
        
        best_model = keras.models.load_model(
            ckpt_path,          # Load best weights
            custom_objects={"GeMPooling2D": GeMPooling2D}
        ) 
        
    preds = predict_with_tta(best_model, test_ds)
    fold_predictions.append(preds)
    
    # Cleanup
    del best_model, train_ds, val_ds
    import gc; gc.collect()

=============== FOLD 1/5 ===============

--- Fold 1: Training Head ---
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
Epoch 1/20
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 21 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1

I0000 00:00:1774131653.826725      62 cuda_dnn.cc:529] Loaded cuDNN version 90300
I0000 00:00:1774131654.688433      63 cuda_dnn.cc:529] Loaded cuDNN version 90300
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1774131655.110621      62 service.cc:148] XLA service 0x7d3d296d97d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1774131655.111583      62 service.cc:156]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
I0000 00:00:1774131655.111602      62 service.cc:156]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
I0000 00:00:1774131655.541290      62 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
E0000 00:00:1774131658.788065      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131658.802422      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131658.937950      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131658.938695      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131659.075115      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131659.213630      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

8/9 ━━━━━━━━━━━━━━━━━━━━ 0s 491ms/step - loss: 0.0279 - mae: 0.1933

E0000 00:00:1774131667.683774      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131667.687819      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131667.825723      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131667.827356      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131667.963115      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131668.097763      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 905ms/step - loss: 0.0280 - mae: 0.1932INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1

E0000 00:00:1774131683.115228      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131683.117082      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131683.263167      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131683.264749      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131683.401246      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131683.535229      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

9/9 ━━━━━━━━━━━━━━━━━━━━ 50s 3s/step - loss: 0.0280 - mae: 0.1932 - val_loss: 0.0079 - val_mae: 0.1069 - learning_rate: 7.0000e-04
Epoch 2/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 545ms/step - loss: 0.0114 - mae: 0.1219INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 786ms/step - loss: 0.0114 - mae: 0.1218 - val_loss: 0.0056 - val_mae: 0.0809 - learning_rate: 7.0000e-04
Epoch 3/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 427ms/step - loss: 0.0148 - mae: 0.1330INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 679ms/step - loss: 0.0148 - mae: 0.1330 - val_loss: 0.0052 - val_mae: 0.0755 - learning_rate: 7.0000e-04
Epoch 4/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 418ms/step - loss: 0.0103 - mae: 0.1030INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 647ms/step - loss: 0.0103 - mae: 0.1030 - val_loss: 0.0049 - val_mae: 0.0751 - learning_rate: 7.0000e-04
Epoch 5/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 679ms/step - loss: 0.0063 - mae: 0.0898 - val_loss: 0.0048 - val_mae: 0.0746 - learning_rate: 7.0000e-04
Epoch 6/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 662ms/step - loss: 0.0067 - mae: 0.0918 - val_loss: 0.0042 - val_mae: 0.0698 - learning_rate: 7.0000e-04
Epoch 7/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 622ms/step - loss: 0.0081 - mae: 0.0964 - val_loss: 0.0038 - val_mae: 0.0655 - learning_rate: 7.0000e-04
Epoch 8/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 640ms/step - loss: 0.0055 - mae: 0.0833 - val_loss: 0.0033 - val_mae: 0.0602 - learning_rate: 7.0000e-04
Epoch 9/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 673ms/step - loss: 0.0055 - mae: 0.0843 - val_loss: 0.0033 - val_mae: 0.0613 - learning_rate: 7.0000e-04
Epoch 10/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 716ms/step - loss: 0.0063 - mae: 0.0832 - val_loss: 0.0030 - val_mae: 0.0574 - learning_rate: 7.0000e-04
Epoch 11/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 655ms/step - loss: 0.0045 - mae: 0.0720 - val_loss: 0.0026 - val_mae: 0.0518 - learning_rate: 7.0000e-04
Epoch 12/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 770ms/step - loss: 0.0055 - mae: 0.0721 - val_loss: 0.0026 - val_mae: 0.0537 - learning_rate: 7.0000e-04
Epoch 13/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 603ms/step - loss: 0.0087 - mae: 0.0955 - val_loss: 0.0032 - val_mae: 0.0630 - learning_rate: 7.0000e-04
Epoch 14/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 694ms/step - loss: 0.0037 - mae: 0.0686 - val_loss: 0.0024 - val_mae: 0.0514 - learning_rate: 7.0000e-05
Epoch 15/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 700ms/step - loss: 0.0047 - mae: 0.0731 - val_loss: 0.0023 - val_mae: 0.0494 - learning_rate: 7.0000e-05
Epoch 16/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 653ms/step - loss: 0.0039 - mae: 0.0691 - val_loss: 0.0023 - val_mae: 0.0504 - learning_rate: 7.0000e-05
Epoch 17/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 778ms/step - loss: 0.0033 - mae: 0.0639 - val_loss: 0.0023 - val_mae: 0.0504 - learning_rate: 7.0000e-06
Epoch 18/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 812ms/step - loss: 0.0029 - mae: 0.0593 - val_loss: 0.0024 - val_mae: 0.0505 - learning_rate: 7.0000e-06
Epoch 19/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 734ms/step - loss: 0.0045 - mae: 0.0688 - val_loss: 0.0024 - val_mae: 0.0505 - learning_rate: 7.0000e-07
Epoch 20/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 712ms/step - loss: 0.0031 - mae: 0.0619 - val_loss: 0.0024 - val_mae: 0.0505 - learning_rate: 7.0000e-07

--- Fold 1: Fine Tuning ---
Epoch 1/30
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 363 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1

E0000 00:00:1774131902.227490      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131902.367112      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131902.374850      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131902.519370      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131902.657490      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131902.972226      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131903.111395      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131903.252213      60 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131903.386557      60 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

17/18 ━━━━━━━━━━━━━━━━━━━━ 0s 929ms/step - loss: 0.0040 - mae: 0.0624

E0000 00:00:1774131925.963464      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131925.976712      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131926.106387      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131926.112400      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131926.547713      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131926.549069      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131926.683866      61 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774131926.685130      62 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0040 - mae: 0.0624   INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 131s 2s/step - loss: 0.0040 - mae: 0.0624 - val_loss: 0.0023 - val_mae: 0.0475
Epoch 2/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0058 - mae: 0.0726 - val_loss: 0.0029 - val_mae: 0.0615
Epoch 3/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0042 - mae: 0.0724 - val_loss: 0.0027 - val_mae: 0.0599
Epoch 4/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0033 - mae: 0.0570 - val_loss: 0.0030 - val_mae: 0.0636
Epoch 5/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0034 - mae: 0.0631 - val_loss: 0.0021 - val_mae: 0.0509
Epoch 6/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0028 - mae: 0.0566 - val_loss: 0.0020 - val_mae: 0.0445
Epoch 7/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0022 - mae: 0.0496 - val_loss: 0.0018 - val_mae: 0.0469
Epoch 8/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0032 - mae: 0.0634 - val_loss: 0.0017 - val_mae: 0.0418
Epoch 9/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0019 - mae: 0.0472 - val_loss: 0.0018 - val_mae: 0.0436
Epoch 10/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0018 - mae: 0.0454 - val_loss: 0.0019 - val_mae: 0.0473
Epoch 11/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0018 - mae: 0.0440 - val_loss: 0.0025 - val_mae: 0.0500
Epoch 12/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 20s 1s/step - loss: 0.0027 - mae: 0.0522 - val_loss: 0.0022 - val_mae: 0.0460
Epoch 13/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0028 - mae: 0.0543 - val_loss: 0.0027 - val_mae: 0.0636
Epoch 14/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0031 - mae: 0.0632 - val_loss: 0.0018 - val_mae: 0.0464
Epoch 15/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0024 - mae: 0.0507 - val_loss: 0.0020 - val_mae: 0.0457
Predicting Fold 1

W0000 00:00:1774132241.775030      20 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "Conv2D" attr { key: "T" value { type: DT_FLOAT } } attr { key: "data_format" value { s: "NCHW" } } attr { key: "dilations" value { list { i: 1 i: 1 i: 1 i: 1 } } } attr { key: "explicit_paddings" value { list { } } } attr { key: "padding" value { s: "VALID" } } attr { key: "strides" value { list { i: 1 i: 1 i: 4 i: 4 } } } attr { key: "use_cudnn_on_gpu" value { b: true } } inputs { dtype: DT_FLOAT shape { dim { } dim { size: 3 } dim { size: 256 } dim { size: 256 } } } inputs { dtype: DT_FLOAT shape { dim { size: 4 } dim { size: 4 } dim { size: 3 } dim { size: 96 } } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "12050" } environment { key: "cudnn" value: "90300" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14426112000 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { dim { } dim { size: 96 } dim { size: 64 } dim { size: 64 } } }
E0000 00:00:1774132245.692912      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774132245.833204      63 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

=============== FOLD 2/5 ===============

--- Fold 2: Training Head ---
Epoch 1/20
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 21 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 794ms/step - loss: 0.0176 - mae: 0.1502INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
9/9 ━━━━━━━━━━━━━━━━━━━━ 42s 3s/step - loss: 0.0177 - mae: 0.1504 - val_loss: 0.0133 - val_mae: 0.1415 - learning_rate: 7.0000e-04
Epoch 2/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 722ms/step - loss: 0.0145 - mae: 0.1433 - val_loss: 0.0119 - val_mae: 0.1084 - learning_rate: 7.0000e-04
Epoch 3/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 761ms/step - loss: 0.0106 - mae: 0.1097 - val_loss: 0.0095 - val_mae: 0.1044 - learning_rate: 7.0000e-04
Epoch 4/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 8s 852ms/step - loss: 0.0080 - mae: 0.0939 - val_loss: 0.0092 - val_mae: 0.0920 - learning_rate: 7.0000e-04
Epoch 5/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 704ms/step - loss: 0.0063 - mae: 0.0860 - val_loss: 0.0081 - val_mae: 0.0833 - learning_rate: 7.0000e-04
Epoch 6/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 798ms/step - loss: 0.0086 - mae: 0.0986 - val_loss: 0.0066 - val_mae: 0.0806 - learning_rate: 7.0000e-04
Epoch 7/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 689ms/step - loss: 0.0055 - mae: 0.0817 - val_loss: 0.0070 - val_mae: 0.0805 - learning_rate: 7.0000e-04
Epoch 8/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 8s 733ms/step - loss: 0.0045 - mae: 0.0733 - val_loss: 0.0082 - val_mae: 0.0838 - learning_rate: 7.0000e-04
Epoch 9/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 721ms/step - loss: 0.0056 - mae: 0.0792 - val_loss: 0.0066 - val_mae: 0.0809 - learning_rate: 7.0000e-05
Epoch 10/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 691ms/step - loss: 0.0034 - mae: 0.0659 - val_loss: 0.0066 - val_mae: 0.0799 - learning_rate: 7.0000e-05
Epoch 11/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 619ms/step - loss: 0.0044 - mae: 0.0753 - val_loss: 0.0067 - val_mae: 0.0795 - learning_rate: 7.0000e-06
Epoch 12/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 739ms/step - loss: 0.0025 - mae: 0.0561 - val_loss: 0.0068 - val_mae: 0.0792 - learning_rate: 7.0000e-06
Epoch 13/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 703ms/step - loss: 0.0038 - mae: 0.0660 - val_loss: 0.0068 - val_mae: 0.0792 - learning_rate: 7.0000e-07

--- Fold 2: Fine Tuning ---
Epoch 1/30
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 363 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0048 - mae: 0.0738   INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 131s 2s/step - loss: 0.0048 - mae: 0.0738 - val_loss: 0.0078 - val_mae: 0.0876
Epoch 2/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0033 - mae: 0.0661 - val_loss: 0.0095 - val_mae: 0.0882
Epoch 3/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0032 - mae: 0.0595 - val_loss: 0.0088 - val_mae: 0.0831
Epoch 4/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0050 - mae: 0.0678 - val_loss: 0.0073 - val_mae: 0.0774
Epoch 5/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0027 - mae: 0.0583 - val_loss: 0.0081 - val_mae: 0.0818
Epoch 6/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0030 - mae: 0.0568 - val_loss: 0.0077 - val_mae: 0.0772
Epoch 7/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0042 - mae: 0.0711 - val_loss: 0.0068 - val_mae: 0.0759
Epoch 8/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0024 - mae: 0.0509 - val_loss: 0.0067 - val_mae: 0.0740
Epoch 9/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0022 - mae: 0.0531 - val_loss: 0.0072 - val_mae: 0.0788
Epoch 10/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0531 - val_loss: 0.0068 - val_mae: 0.0751
Epoch 11/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0499 - val_loss: 0.0071 - val_mae: 0.0733
Epoch 12/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0015 - mae: 0.0424 - val_loss: 0.0068 - val_mae: 0.0729
Epoch 13/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0018 - mae: 0.0459 - val_loss: 0.0073 - val_mae: 0.0743
Epoch 14/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0021 - mae: 0.0493 - val_loss: 0.0087 - val_mae: 0.0855
Epoch 15/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0020 - mae: 0.0506 - val_loss: 0.0062 - val_mae: 0.0737
Epoch 16/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0015 - mae: 0.0410 - val_loss: 0.0068 - val_mae: 0.0710
Epoch 17/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0014 - mae: 0.0402 - val_loss: 0.0061 - val_mae: 0.0697
Epoch 18/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0015 - mae: 0.0430 - val_loss: 0.0068 - val_mae: 0.0754
Epoch 19/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0017 - mae: 0.0442 - val_loss: 0.0066 - val_mae: 0.0729
Epoch 20/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0012 - mae: 0.0385 - val_loss: 0.0062 - val_mae: 0.0671
Epoch 21/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0014 - mae: 0.0421 - val_loss: 0.0058 - val_mae: 0.0675
Epoch 22/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0019 - mae: 0.0493 - val_loss: 0.0069 - val_mae: 0.0703
Epoch 23/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0011 - mae: 0.0369 - val_loss: 0.0071 - val_mae: 0.0709
Epoch 24/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0012 - mae: 0.0386 - val_loss: 0.0067 - val_mae: 0.0683
Epoch 25/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0017 - mae: 0.0461 - val_loss: 0.0063 - val_mae: 0.0683
Epoch 26/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0012 - mae: 0.0380 - val_loss: 0.0062 - val_mae: 0.0695
Epoch 27/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0011 - mae: 0.0385 - val_loss: 0.0065 - val_mae: 0.0691
Epoch 28/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0418 - val_loss: 0.0059 - val_mae: 0.0698
Predicting Fold 2

W0000 00:00:1774133077.565962      20 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "Conv2D" attr { key: "T" value { type: DT_FLOAT } } attr { key: "data_format" value { s: "NCHW" } } attr { key: "dilations" value { list { i: 1 i: 1 i: 1 i: 1 } } } attr { key: "explicit_paddings" value { list { } } } attr { key: "padding" value { s: "VALID" } } attr { key: "strides" value { list { i: 1 i: 1 i: 4 i: 4 } } } attr { key: "use_cudnn_on_gpu" value { b: true } } inputs { dtype: DT_FLOAT shape { dim { } dim { size: 3 } dim { size: 256 } dim { size: 256 } } } inputs { dtype: DT_FLOAT shape { dim { size: 4 } dim { size: 4 } dim { size: 3 } dim { size: 96 } } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "12050" } environment { key: "cudnn" value: "90300" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14426112000 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { dim { } dim { size: 96 } dim { size: 64 } dim { size: 64 } } }

=============== FOLD 3/5 ===============

--- Fold 3: Training Head ---
Epoch 1/20
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 21 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 745ms/step - loss: 0.0459 - mae: 0.2340INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1

E0000 00:00:1774133145.200465      60 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774133145.354896      60 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.
E0000 00:00:1774133145.489620      60 gpu_timer.cc:82] Delay kernel timed out: measured time has sub-optimal accuracy. There may be a missing warmup execution, please investigate in Nsight Systems.

9/9 ━━━━━━━━━━━━━━━━━━━━ 46s 3s/step - loss: 0.0456 - mae: 0.2329 - val_loss: 0.0121 - val_mae: 0.1107 - learning_rate: 7.0000e-04
Epoch 2/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 708ms/step - loss: 0.0077 - mae: 0.0967 - val_loss: 0.0071 - val_mae: 0.0930 - learning_rate: 7.0000e-04
Epoch 3/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 724ms/step - loss: 0.0076 - mae: 0.0947 - val_loss: 0.0058 - val_mae: 0.0765 - learning_rate: 7.0000e-04
Epoch 4/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 779ms/step - loss: 0.0102 - mae: 0.1075 - val_loss: 0.0052 - val_mae: 0.0676 - learning_rate: 7.0000e-04
Epoch 5/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 725ms/step - loss: 0.0080 - mae: 0.0905 - val_loss: 0.0041 - val_mae: 0.0634 - learning_rate: 7.0000e-04
Epoch 6/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 643ms/step - loss: 0.0060 - mae: 0.0842 - val_loss: 0.0044 - val_mae: 0.0667 - learning_rate: 7.0000e-04
Epoch 7/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 740ms/step - loss: 0.0049 - mae: 0.0739 - val_loss: 0.0035 - val_mae: 0.0619 - learning_rate: 7.0000e-04
Epoch 8/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 687ms/step - loss: 0.0037 - mae: 0.0631 - val_loss: 0.0037 - val_mae: 0.0684 - learning_rate: 7.0000e-04
Epoch 9/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 709ms/step - loss: 0.0050 - mae: 0.0781 - val_loss: 0.0038 - val_mae: 0.0622 - learning_rate: 7.0000e-04
Epoch 10/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 732ms/step - loss: 0.0058 - mae: 0.0849 - val_loss: 0.0036 - val_mae: 0.0650 - learning_rate: 7.0000e-05
Epoch 11/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 672ms/step - loss: 0.0050 - mae: 0.0783 - val_loss: 0.0038 - val_mae: 0.0693 - learning_rate: 7.0000e-05
Epoch 12/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 779ms/step - loss: 0.0035 - mae: 0.0614 - val_loss: 0.0037 - val_mae: 0.0674 - learning_rate: 7.0000e-06
Epoch 13/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 752ms/step - loss: 0.0037 - mae: 0.0649 - val_loss: 0.0035 - val_mae: 0.0656 - learning_rate: 7.0000e-06
Epoch 14/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 715ms/step - loss: 0.0060 - mae: 0.0791 - val_loss: 0.0035 - val_mae: 0.0655 - learning_rate: 7.0000e-07
Epoch 15/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 666ms/step - loss: 0.0044 - mae: 0.0731 - val_loss: 0.0035 - val_mae: 0.0653 - learning_rate: 7.0000e-07
Epoch 16/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 710ms/step - loss: 0.0036 - mae: 0.0653 - val_loss: 0.0035 - val_mae: 0.0653 - learning_rate: 7.0000e-08
Epoch 17/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 732ms/step - loss: 0.0036 - mae: 0.0645 - val_loss: 0.0035 - val_mae: 0.0652 - learning_rate: 7.0000e-08
Epoch 18/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 742ms/step - loss: 0.0042 - mae: 0.0729 - val_loss: 0.0035 - val_mae: 0.0652 - learning_rate: 7.0000e-09
Epoch 19/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 756ms/step - loss: 0.0038 - mae: 0.0630 - val_loss: 0.0035 - val_mae: 0.0652 - learning_rate: 7.0000e-09
Epoch 20/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 639ms/step - loss: 0.0042 - mae: 0.0678 - val_loss: 0.0035 - val_mae: 0.0652 - learning_rate: 7.0000e-10

--- Fold 3: Fine Tuning ---
Epoch 1/30
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 363 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0049 - mae: 0.0809   INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 133s 2s/step - loss: 0.0049 - mae: 0.0809 - val_loss: 0.0056 - val_mae: 0.0725
Epoch 2/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0032 - mae: 0.0651 - val_loss: 0.0049 - val_mae: 0.0814
Epoch 3/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0034 - mae: 0.0670 - val_loss: 0.0050 - val_mae: 0.0763
Epoch 4/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0040 - mae: 0.0657 - val_loss: 0.0034 - val_mae: 0.0607
Epoch 5/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0024 - mae: 0.0559 - val_loss: 0.0037 - val_mae: 0.0571
Epoch 6/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0031 - mae: 0.0556 - val_loss: 0.0035 - val_mae: 0.0639
Epoch 7/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0026 - mae: 0.0587 - val_loss: 0.0028 - val_mae: 0.0525
Epoch 8/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0025 - mae: 0.0528 - val_loss: 0.0035 - val_mae: 0.0623
Epoch 9/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0480 - val_loss: 0.0032 - val_mae: 0.0569
Epoch 10/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0456 - val_loss: 0.0050 - val_mae: 0.0784
Epoch 11/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0031 - mae: 0.0650 - val_loss: 0.0034 - val_mae: 0.0631
Epoch 12/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0023 - mae: 0.0521 - val_loss: 0.0033 - val_mae: 0.0540
Epoch 13/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0019 - mae: 0.0490 - val_loss: 0.0028 - val_mae: 0.0536
Epoch 14/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0018 - mae: 0.0434 - val_loss: 0.0031 - val_mae: 0.0608
Epoch 15/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 25s 1s/step - loss: 0.0017 - mae: 0.0460 - val_loss: 0.0028 - val_mae: 0.0502
Epoch 16/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0013 - mae: 0.0409 - val_loss: 0.0030 - val_mae: 0.0535
Epoch 17/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0016 - mae: 0.0445 - val_loss: 0.0035 - val_mae: 0.0603
Epoch 18/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0014 - mae: 0.0409 - val_loss: 0.0030 - val_mae: 0.0556
Epoch 19/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0462 - val_loss: 0.0030 - val_mae: 0.0521
Epoch 20/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0018 - mae: 0.0474 - val_loss: 0.0033 - val_mae: 0.0541
Epoch 21/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0017 - mae: 0.0477 - val_loss: 0.0033 - val_mae: 0.0614
Epoch 22/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0018 - mae: 0.0438 - val_loss: 0.0030 - val_mae: 0.0527
Predicting Fold 3

W0000 00:00:1774133851.739050      20 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "Conv2D" attr { key: "T" value { type: DT_FLOAT } } attr { key: "data_format" value { s: "NCHW" } } attr { key: "dilations" value { list { i: 1 i: 1 i: 1 i: 1 } } } attr { key: "explicit_paddings" value { list { } } } attr { key: "padding" value { s: "VALID" } } attr { key: "strides" value { list { i: 1 i: 1 i: 4 i: 4 } } } attr { key: "use_cudnn_on_gpu" value { b: true } } inputs { dtype: DT_FLOAT shape { dim { } dim { size: 3 } dim { size: 256 } dim { size: 256 } } } inputs { dtype: DT_FLOAT shape { dim { size: 4 } dim { size: 4 } dim { size: 3 } dim { size: 96 } } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "12050" } environment { key: "cudnn" value: "90300" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14426112000 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { dim { } dim { size: 96 } dim { size: 64 } dim { size: 64 } } }

=============== FOLD 4/5 ===============

--- Fold 4: Training Head ---
Epoch 1/20
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 21 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 739ms/step - loss: 0.0276 - mae: 0.1787INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
9/9 ━━━━━━━━━━━━━━━━━━━━ 43s 3s/step - loss: 0.0276 - mae: 0.1786 - val_loss: 0.0064 - val_mae: 0.0866 - learning_rate: 7.0000e-04
Epoch 2/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 8s 796ms/step - loss: 0.0107 - mae: 0.1111 - val_loss: 0.0061 - val_mae: 0.0771 - learning_rate: 7.0000e-04
Epoch 3/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 675ms/step - loss: 0.0087 - mae: 0.0998 - val_loss: 0.0051 - val_mae: 0.0802 - learning_rate: 7.0000e-04
Epoch 4/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 722ms/step - loss: 0.0092 - mae: 0.1038 - val_loss: 0.0035 - val_mae: 0.0589 - learning_rate: 7.0000e-04
Epoch 5/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 727ms/step - loss: 0.0052 - mae: 0.0810 - val_loss: 0.0030 - val_mae: 0.0569 - learning_rate: 7.0000e-04
Epoch 6/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 788ms/step - loss: 0.0094 - mae: 0.0948 - val_loss: 0.0029 - val_mae: 0.0551 - learning_rate: 7.0000e-04
Epoch 7/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 657ms/step - loss: 0.0049 - mae: 0.0690 - val_loss: 0.0027 - val_mae: 0.0558 - learning_rate: 7.0000e-04
Epoch 8/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 671ms/step - loss: 0.0054 - mae: 0.0778 - val_loss: 0.0029 - val_mae: 0.0568 - learning_rate: 7.0000e-04
Epoch 9/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 701ms/step - loss: 0.0044 - mae: 0.0694 - val_loss: 0.0028 - val_mae: 0.0541 - learning_rate: 7.0000e-04
Epoch 10/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 747ms/step - loss: 0.0062 - mae: 0.0783 - val_loss: 0.0026 - val_mae: 0.0527 - learning_rate: 7.0000e-05
Epoch 11/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 780ms/step - loss: 0.0058 - mae: 0.0827 - val_loss: 0.0026 - val_mae: 0.0535 - learning_rate: 7.0000e-05
Epoch 12/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 693ms/step - loss: 0.0036 - mae: 0.0657 - val_loss: 0.0026 - val_mae: 0.0534 - learning_rate: 7.0000e-05
Epoch 13/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 662ms/step - loss: 0.0035 - mae: 0.0667 - val_loss: 0.0026 - val_mae: 0.0534 - learning_rate: 7.0000e-06
Epoch 14/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 670ms/step - loss: 0.0038 - mae: 0.0675 - val_loss: 0.0025 - val_mae: 0.0532 - learning_rate: 7.0000e-06
Epoch 15/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 683ms/step - loss: 0.0064 - mae: 0.0834 - val_loss: 0.0025 - val_mae: 0.0532 - learning_rate: 7.0000e-07
Epoch 16/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 715ms/step - loss: 0.0042 - mae: 0.0678 - val_loss: 0.0025 - val_mae: 0.0532 - learning_rate: 7.0000e-07
Epoch 17/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 706ms/step - loss: 0.0047 - mae: 0.0720 - val_loss: 0.0025 - val_mae: 0.0532 - learning_rate: 7.0000e-08
Epoch 18/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 673ms/step - loss: 0.0027 - mae: 0.0567 - val_loss: 0.0025 - val_mae: 0.0532 - learning_rate: 7.0000e-08
Epoch 19/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 674ms/step - loss: 0.0048 - mae: 0.0731 - val_loss: 0.0025 - val_mae: 0.0532 - learning_rate: 7.0000e-09
Epoch 20/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 710ms/step - loss: 0.0046 - mae: 0.0727 - val_loss: 0.0025 - val_mae: 0.0532 - learning_rate: 7.0000e-09

--- Fold 4: Fine Tuning ---
Epoch 1/30
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 363 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0055 - mae: 0.0817   INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 125s 2s/step - loss: 0.0055 - mae: 0.0817 - val_loss: 0.0024 - val_mae: 0.0536
Epoch 2/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0046 - mae: 0.0784 - val_loss: 0.0023 - val_mae: 0.0532
Epoch 3/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0030 - mae: 0.0585 - val_loss: 0.0017 - val_mae: 0.0447
Epoch 4/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0035 - mae: 0.0613 - val_loss: 0.0019 - val_mae: 0.0472
Epoch 5/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0034 - mae: 0.0657 - val_loss: 0.0020 - val_mae: 0.0441
Epoch 6/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0046 - mae: 0.0671 - val_loss: 0.0016 - val_mae: 0.0432
Epoch 7/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0023 - mae: 0.0517 - val_loss: 0.0018 - val_mae: 0.0453
Epoch 8/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0019 - mae: 0.0496 - val_loss: 0.0024 - val_mae: 0.0464
Epoch 9/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0026 - mae: 0.0531 - val_loss: 0.0017 - val_mae: 0.0454
Epoch 10/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0031 - mae: 0.0598 - val_loss: 0.0024 - val_mae: 0.0557
Epoch 11/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0037 - mae: 0.0678 - val_loss: 0.0017 - val_mae: 0.0411
Epoch 12/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0022 - mae: 0.0507 - val_loss: 0.0021 - val_mae: 0.0488
Epoch 13/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0019 - mae: 0.0448 - val_loss: 0.0016 - val_mae: 0.0404
Epoch 14/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0472 - val_loss: 0.0023 - val_mae: 0.0472
Epoch 15/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0027 - mae: 0.0572 - val_loss: 0.0015 - val_mae: 0.0386
Epoch 16/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0027 - mae: 0.0519 - val_loss: 0.0017 - val_mae: 0.0455
Epoch 17/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0025 - mae: 0.0534 - val_loss: 0.0014 - val_mae: 0.0404
Epoch 18/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0502 - val_loss: 0.0016 - val_mae: 0.0398
Epoch 19/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0022 - mae: 0.0487 - val_loss: 0.0015 - val_mae: 0.0395
Epoch 20/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0017 - mae: 0.0449 - val_loss: 0.0015 - val_mae: 0.0400
Epoch 21/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0019 - mae: 0.0463 - val_loss: 0.0015 - val_mae: 0.0399
Epoch 22/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0017 - mae: 0.0460 - val_loss: 0.0013 - val_mae: 0.0383
Epoch 23/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0015 - mae: 0.0413 - val_loss: 0.0013 - val_mae: 0.0378
Epoch 24/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 8.0647e-04 - mae: 0.0307 - val_loss: 0.0014 - val_mae: 0.0393
Epoch 25/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0017 - mae: 0.0446 - val_loss: 0.0022 - val_mae: 0.0520
Epoch 26/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0019 - mae: 0.0465 - val_loss: 0.0013 - val_mae: 0.0388
Epoch 27/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0015 - mae: 0.0417 - val_loss: 0.0013 - val_mae: 0.0373
Epoch 28/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 8.4054e-04 - mae: 0.0322 - val_loss: 0.0014 - val_mae: 0.0377
Epoch 29/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 8.2875e-04 - mae: 0.0296 - val_loss: 0.0013 - val_mae: 0.0359
Epoch 30/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0015 - mae: 0.0424 - val_loss: 0.0013 - val_mae: 0.0383
Predicting Fold 4

W0000 00:00:1774134768.637288      20 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "Conv2D" attr { key: "T" value { type: DT_FLOAT } } attr { key: "data_format" value { s: "NCHW" } } attr { key: "dilations" value { list { i: 1 i: 1 i: 1 i: 1 } } } attr { key: "explicit_paddings" value { list { } } } attr { key: "padding" value { s: "VALID" } } attr { key: "strides" value { list { i: 1 i: 1 i: 4 i: 4 } } } attr { key: "use_cudnn_on_gpu" value { b: true } } inputs { dtype: DT_FLOAT shape { dim { } dim { size: 3 } dim { size: 256 } dim { size: 256 } } } inputs { dtype: DT_FLOAT shape { dim { size: 4 } dim { size: 4 } dim { size: 3 } dim { size: 96 } } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "12050" } environment { key: "cudnn" value: "90300" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14426112000 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { dim { } dim { size: 96 } dim { size: 64 } dim { size: 64 } } }

=============== FOLD 5/5 ===============

--- Fold 5: Training Head ---
Epoch 1/20
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 21 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 714ms/step - loss: 0.0206 - mae: 0.1659INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
9/9 ━━━━━━━━━━━━━━━━━━━━ 43s 3s/step - loss: 0.0206 - mae: 0.1659 - val_loss: 0.0103 - val_mae: 0.1187 - learning_rate: 7.0000e-04
Epoch 2/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 737ms/step - loss: 0.0149 - mae: 0.1376 - val_loss: 0.0072 - val_mae: 0.0842 - learning_rate: 7.0000e-04
Epoch 3/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 679ms/step - loss: 0.0100 - mae: 0.1027 - val_loss: 0.0063 - val_mae: 0.0800 - learning_rate: 7.0000e-04
Epoch 4/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 711ms/step - loss: 0.0070 - mae: 0.0905 - val_loss: 0.0048 - val_mae: 0.0669 - learning_rate: 7.0000e-04
Epoch 5/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 671ms/step - loss: 0.0056 - mae: 0.0828 - val_loss: 0.0049 - val_mae: 0.0733 - learning_rate: 7.0000e-04
Epoch 6/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 682ms/step - loss: 0.0067 - mae: 0.0873 - val_loss: 0.0049 - val_mae: 0.0718 - learning_rate: 7.0000e-04
Epoch 7/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 636ms/step - loss: 0.0073 - mae: 0.0946 - val_loss: 0.0049 - val_mae: 0.0783 - learning_rate: 7.0000e-05
Epoch 8/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 664ms/step - loss: 0.0043 - mae: 0.0734 - val_loss: 0.0044 - val_mae: 0.0720 - learning_rate: 7.0000e-05
Epoch 9/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 662ms/step - loss: 0.0041 - mae: 0.0715 - val_loss: 0.0042 - val_mae: 0.0665 - learning_rate: 7.0000e-05
Epoch 10/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 631ms/step - loss: 0.0055 - mae: 0.0781 - val_loss: 0.0042 - val_mae: 0.0707 - learning_rate: 7.0000e-05
Epoch 11/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 670ms/step - loss: 0.0041 - mae: 0.0687 - val_loss: 0.0040 - val_mae: 0.0652 - learning_rate: 7.0000e-05
Epoch 12/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 667ms/step - loss: 0.0050 - mae: 0.0729 - val_loss: 0.0040 - val_mae: 0.0674 - learning_rate: 7.0000e-05
Epoch 13/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 799ms/step - loss: 0.0046 - mae: 0.0725 - val_loss: 0.0040 - val_mae: 0.0658 - learning_rate: 7.0000e-05
Epoch 14/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 661ms/step - loss: 0.0033 - mae: 0.0645 - val_loss: 0.0040 - val_mae: 0.0659 - learning_rate: 7.0000e-06
Epoch 15/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 662ms/step - loss: 0.0040 - mae: 0.0662 - val_loss: 0.0040 - val_mae: 0.0660 - learning_rate: 7.0000e-06
Epoch 16/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 628ms/step - loss: 0.0042 - mae: 0.0721 - val_loss: 0.0040 - val_mae: 0.0660 - learning_rate: 7.0000e-07
Epoch 17/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 755ms/step - loss: 0.0039 - mae: 0.0679 - val_loss: 0.0040 - val_mae: 0.0661 - learning_rate: 7.0000e-07
Epoch 18/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 657ms/step - loss: 0.0039 - mae: 0.0694 - val_loss: 0.0040 - val_mae: 0.0661 - learning_rate: 7.0000e-08
Epoch 19/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 656ms/step - loss: 0.0051 - mae: 0.0743 - val_loss: 0.0040 - val_mae: 0.0661 - learning_rate: 7.0000e-08
Epoch 20/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 641ms/step - loss: 0.0044 - mae: 0.0706 - val_loss: 0.0040 - val_mae: 0.0661 - learning_rate: 7.0000e-09

--- Fold 5: Fine Tuning ---
Epoch 1/30
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 363 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0040 - mae: 0.0693   INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
INFO:tensorflow:Collective all_reduce tensors: 1 all_reduces, num_devices = 2, group_size = 2, implementation = CommunicationImplementation.NCCL, num_packs = 1
18/18 ━━━━━━━━━━━━━━━━━━━━ 127s 2s/step - loss: 0.0040 - mae: 0.0694 - val_loss: 0.0041 - val_mae: 0.0716
Epoch 2/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.0065 - mae: 0.0948 - val_loss: 0.0033 - val_mae: 0.0606
Epoch 3/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0045 - mae: 0.0693 - val_loss: 0.0037 - val_mae: 0.0600
Epoch 4/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0045 - mae: 0.0676 - val_loss: 0.0041 - val_mae: 0.0633
Epoch 5/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0031 - mae: 0.0625 - val_loss: 0.0027 - val_mae: 0.0515
Epoch 6/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0029 - mae: 0.0582 - val_loss: 0.0032 - val_mae: 0.0568
Epoch 7/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0032 - mae: 0.0608 - val_loss: 0.0029 - val_mae: 0.0560
Epoch 8/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0028 - mae: 0.0596 - val_loss: 0.0027 - val_mae: 0.0540
Epoch 9/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0023 - mae: 0.0512 - val_loss: 0.0030 - val_mae: 0.0529
Epoch 10/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0034 - mae: 0.0619 - val_loss: 0.0033 - val_mae: 0.0537
Epoch 11/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.0029 - mae: 0.0529 - val_loss: 0.0025 - val_mae: 0.0497
Epoch 12/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0021 - mae: 0.0529 - val_loss: 0.0027 - val_mae: 0.0519
Epoch 13/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0018 - mae: 0.0444 - val_loss: 0.0027 - val_mae: 0.0510
Epoch 14/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0021 - mae: 0.0497 - val_loss: 0.0027 - val_mae: 0.0502
Epoch 15/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0015 - mae: 0.0418 - val_loss: 0.0030 - val_mae: 0.0533
Epoch 16/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0020 - mae: 0.0449 - val_loss: 0.0027 - val_mae: 0.0499
Epoch 17/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0019 - mae: 0.0456 - val_loss: 0.0028 - val_mae: 0.0533
Epoch 18/30
18/18 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.0021 - mae: 0.0521 - val_loss: 0.0028 - val_mae: 0.0542
Predicting Fold 5

W0000 00:00:1774135444.853710      20 op_level_cost_estimator.cc:699] Error in PredictCost() for the op: op: "Conv2D" attr { key: "T" value { type: DT_FLOAT } } attr { key: "data_format" value { s: "NCHW" } } attr { key: "dilations" value { list { i: 1 i: 1 i: 1 i: 1 } } } attr { key: "explicit_paddings" value { list { } } } attr { key: "padding" value { s: "VALID" } } attr { key: "strides" value { list { i: 1 i: 1 i: 4 i: 4 } } } attr { key: "use_cudnn_on_gpu" value { b: true } } inputs { dtype: DT_FLOAT shape { dim { } dim { size: 3 } dim { size: 256 } dim { size: 256 } } } inputs { dtype: DT_FLOAT shape { dim { size: 4 } dim { size: 4 } dim { size: 3 } dim { size: 96 } } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "12050" } environment { key: "cudnn" value: "90300" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14426112000 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { dim { } dim { size: 96 } dim { size: 64 } dim { size: 64 } } }

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7d394424b7e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [14]:
# --- Ensamble avereging

# Average the predictions
avg_preds_scaled = np.mean(fold_predictions, axis=0)

# Clip & Convert to Grams (denormalize)
preds_3_grams = np.clip(avg_preds_scaled, 0, None) * TARGET_SCALER

In [15]:
# --- Physics & Submission 
final_preds_5 = []        # there are 5 things to predict

for row in preds_3_grams:
    total = row[0]        # Dry_Total_g  (total biomass)
    gdm   = row[1]        # GDM_g        (green dry matter)
    green = row[2]        # Dry_Green_g  (dry green biomass)
    
    # Physics Constraints

    if gdm > total:       # gdm must be <= than total biomass
        gdm = total       

    if green > gdm:       # dry green must be <= than gdm 
        green = gdm
        
    dead = total - gdm              # dry dead = total biomass - green dry matter
    clover = gdm - green            # dry clover = green dry matter - dry green biomass
    
    final_preds_5.append([green, dead, clover, gdm, total])

# Map to Submission
pred_map = {path: preds for path, preds in zip(unique_test_df['image_path'], final_preds_5)}
target_indices = {'Dry_Green_g': 0, 'Dry_Dead_g': 1, 'Dry_Clover_g': 2, 'GDM_g': 3, 'Dry_Total_g': 4}

submission_rows = []
for _, row in raw_test_df.iterrows():
    img_name = row['image_path']
    t_name = row['target_name']
    val = pred_map[img_name][target_indices[t_name]]
    submission_rows.append({'sample_id': row['sample_id'], 'target': float(val)})

sub_df = pd.DataFrame(submission_rows)
sub_df.to_csv('submission.csv', index=False)
print(sub_df.head())

                    sample_id     target
0  ID1001187975__Dry_Clover_g   0.000000
1    ID1001187975__Dry_Dead_g  21.953606
2   ID1001187975__Dry_Green_g  33.913876
3   ID1001187975__Dry_Total_g  55.867481
4         ID1001187975__GDM_g  33.913876